import type { SearchResult } from '../types'

// 게스트 계정 로그아웃 시 컬렉션을 이 초기 상태로 리셋한다.
export const GUEST_INITIAL_COLLECTION: SearchResult[] = [
  {
    discogs_id: '15176873',
    album_name: '전설',
    artist_name: '잔나비',
    cover_url:
      'https://i.discogs.com/nMIZu2Oig1DwzVudpen23Iu5aEs4az6I7wafh_3Wy3c/rs:fit/g:sm/q:90/h:598/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE1MTc2/ODczLTE2MTEwNjc5/ODEtNjI0Ni5qcGVn.jpeg',
    year: '2020',
    genres: ['Rock', 'Pop'],
    tracklist: [
      { position: 'A1', title: '나의 기쁨 나의 노래 (Intro) ; Good Good Night', duration: '3:36' },
      { position: 'A2', title: '투게더! ; Together!', duration: '3:06' },
      { position: 'A3', title: '조이풀 조이풀 ; Joyful Joyful', duration: '4:03' },
      { position: 'A4', title: '거울 ; Mirror', duration: '3:20' },
      { position: 'A5', title: '우리 애는요 ; About a Boy', duration: '2:39' },
      { position: 'A6', title: 'Dolmaro', duration: '3:54' },
      { position: 'B1', title: '전설 ; Legend', duration: '3:47' },
      { position: 'B2', title: '주저하는 연인들을 위해 ; For Lovers Who Hesitate', duration: '4:25' },
      { position: 'B3', title: '신나는 잠 ; Geum Ui Hwan Hyang', duration: '3:42' },
      { position: 'B4', title: '나쁜 꿈 ; Bad Dreams', duration: '4:52' },
      { position: 'B5', title: '새 어둠 새 눈 ; Land of Night', duration: '4:26' },
      { position: 'B6', title: '꿈과 책과 힘과 벽 ; Dreams, Books, Power and Walls', duration: '4:57' },
    ],
  },
  {
    discogs_id: '15993459',
    album_name: 'Monkey Hotel',
    artist_name: '잔나비',
    cover_url:
      'https://i.discogs.com/Stf5Ffh_MzENbAm1uTsExQruvJ5aTHo91bIK8zNV_LI/rs:fit/g:sm/q:90/h:488/w:488/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE1OTkz/NDU5LTE2MDUxNzM4/MTgtNzc1Ni5qcGVn.jpeg',
    year: '2016',
    genres: ['Rock', 'Blues', 'Pop'],
    tracklist: [
      { position: 'A1', title: 'Goodnight (intro)', duration: '1:08' },
      { position: 'A2', title: '뜨거운 여름밤은 가고 남은건 볼품 없지만', duration: '4:02' },
      { position: 'A3', title: 'Surprise!', duration: '3:22' },
      { position: 'A4', title: 'Wish', duration: '3:49' },
      { position: 'A5', title: 'The Secret Of Hard Rock', duration: '3:16' },
      { position: 'B1', title: 'HONG KONG', duration: '3:37' },
      { position: 'B2', title: '꿈나라 별나라', duration: '2:43' },
      { position: 'B3', title: 'JUNGLE', duration: '3:09' },
      { position: 'B4', title: 'MONKEY HOTEL (Finale)', duration: '2:00' },
      { position: 'B5', title: '왕눈이왈츠 (Bonus Track)', duration: '2:17' },
    ],
  },
  {
    discogs_id: '17638198',
    album_name: '소곡집 I',
    artist_name: '잔나비',
    cover_url:
      'https://i.discogs.com/OUpk4AIGYML6RBf-Mr7RI0TUqXB-Ge1KduBX11kl1nA/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE3NjM4/MTk4LTE2MTQ1ODc2/MjktMTcxOS5qcGVn.jpeg',
    year: '2021',
    genres: ['Rock', 'Blues', 'Pop'],
    tracklist: [
      { position: 'A1', title: '가을밤에 든 생각', duration: '3:36' },
      { position: 'A2', title: '한걸음', duration: '3:22' },
      { position: 'A3', title: '그 밤 그 밤', duration: '2:55' },
      { position: 'B1', title: '늙은 개', duration: '2:23' },
      { position: 'B2', title: '작전명 청-춘!', duration: '3:58' },
      { position: 'B3', title: '가을밤에 든 생각 (B ver.)', duration: '' },
    ],
  },
  {
    discogs_id: '21237181',
    album_name: '환상의 나라 (The Land Of Fantasy)',
    artist_name: '잔나비',
    cover_url:
      'https://i.discogs.com/D_6_LxJzlVKK0RWTBXI5sFgzIFof2TELpqWarNNEle8/rs:fit/g:sm/q:90/h:604/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIxMjM3/MTgxLTE2Mzg3MDk0/MDEtMjczOC5wbmc.jpeg',
    year: '2021',
    genres: ['Rock', 'Pop'],
    tracklist: [
      { position: 'A1', title: '환상의 나라', duration: '1:07' },
      { position: 'A2', title: '용맹한 발걸음이여', duration: '3:15' },
      { position: 'A3', title: '비틀파워!', duration: '3:05' },
      { position: 'A4', title: '고백극장', duration: '3:08' },
      { position: 'A5', title: '로맨스의 왕', duration: '3:43' },
      { position: 'A6', title: '페어웰 투 암스! + 요람송가', duration: '4:39' },
      { position: 'B1', title: '소년 클레이 피전', duration: '1:45' },
      { position: 'B2', title: '누구를 위한 노래였던가', duration: '3:42' },
      { position: 'B3', title: '밤의 공원', duration: '4:46' },
      { position: 'B4', title: '외딴섬 로맨틱', duration: '3:42' },
      { position: 'B5', title: '블루버드, 스프레드 유어 윙스!', duration: '2:12' },
      { position: 'B6', title: '굿바이 환상의 나라', duration: '1:15' },
      { position: 'B7', title: '컴백홈', duration: '3:21' },
    ],
  },
  {
    discogs_id: '21303211',
    album_name: 'Next Episode',
    artist_name: 'AKMU*',
    cover_url:
      'https://i.discogs.com/CSIFOmx6TpSy1puZh-E4nlm8vYbTqOVJtl0LA6vbjno/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIxMzAz/MjExLTE3NzQ5MjA2/NTctNDU2Ny5wbmc.jpeg',
    year: '2022',
    genres: ['Pop'],
    tracklist: [
      { position: 'A1', title: '전쟁터', duration: '3:53' },
      { position: 'A2', title: '낙하', duration: '3:33' },
      { position: 'A3', title: 'Bench', duration: '3:45' },
      { position: 'A4', title: '째깍 째깍 째깍', duration: '3:57' },
      { position: 'B1', title: '맞짱', duration: '3:12' },
      { position: 'B2', title: 'Stupid Love Song', duration: '3:09' },
      { position: 'B3', title: 'Everest', duration: '3:16' },
    ],
  },
  {
    discogs_id: '23425748',
    album_name: 'PSY 9th / 싸다9',
    artist_name: 'Psy (7)',
    cover_url:
      'https://i.discogs.com/Ubo_yJ2mXAgqFFnTcb2Hv6h_DbxfIfCZ6q8_F3BJ9dM/rs:fit/g:sm/q:90/h:602/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIzNDI1/NzQ4LTE2NTcyMTMy/NjYtMTc1Mi5qcGVn.jpeg',
    year: '2022',
    genres: ['Electronic', 'Hip Hop', 'Funk / Soul', 'Pop'],
    tracklist: [
      { position: '1', title: '9INTRO', duration: '2:47' },
      { position: '2', title: 'That That ', duration: '2:55' },
      { position: '3', title: 'Celeb', duration: '3:20' },
      { position: '4', title: 'You Move Me', duration: '3:41' },
      { position: '5', title: 'Sleepless', duration: '3:06' },
      { position: '6', title: 'GANJI', duration: '2:52' },
      { position: '7', title: 'Now', duration: '3:29' },
      { position: '8', title: 'Happier', duration: '4:12' },
      { position: '9', title: 'Hello Monday', duration: '2:52' },
      { position: '10', title: 'Everyday', duration: '4:37' },
      { position: '11', title: 'forEVER', duration: '3:29' },
      { position: '12', title: 'Dear Me', duration: '4:06' },
    ],
  },
  {
    discogs_id: '26759546',
    album_name: '소곡집 II : 초록을거머쥔우리는',
    artist_name: '잔나비',
    cover_url:
      'https://i.discogs.com/24mXdQ-Sk5IONzuNmTMo9LIXAK-0VR8XEVb8NGG6dfw/rs:fit/g:sm/q:90/h:237/w:236/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI2NzU5/NTQ2LTE2ODE0ODkx/NTEtOTMwOC5wbmc.jpeg',
    year: '2023',
    genres: ['Rock', 'Pop'],
    tracklist: [
      { position: '1', title: '레이디버드', duration: '3:27' },
      { position: '2', title: '초록을거머쥔우리는', duration: '3:24' },
      { position: '3', title: '여름가을겨울 봄.', duration: '3:02' },
      { position: '4', title: '슬픔이여안녕', duration: '3:56' },
      { position: '5', title: '즐거운나의집 demo ver. (Bonus track)', duration: '' },
    ],
  },
  {
    discogs_id: '33970398',
    album_name: '사운드 오브 뮤직 pt.1',
    artist_name: '잔나비',
    cover_url:
      'https://i.discogs.com/WZgL9em77_AgruPYCb2K6_o4jZpNDaTgmkdCz1VH-jU/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMzOTcw/Mzk4LTE3NDcxNTk5/MjEtNDgyMS5qcGVn.jpeg',
    year: '2025',
    genres: ['Electronic', 'Rock'],
    tracklist: [
      { position: '1', title: '뮤직', duration: '1:45' },
      { position: '2', title: 'FLASH', duration: '3:13' },
      { position: '3', title: '아윌다이포유♥︎×3', duration: '3:18' },
      { position: '4', title: '사랑의이름으로! (feat. 카리나 of aespa)', duration: '3:25' },
      { position: '5', title: '옥상에서 혼자 노을을 봤음', duration: '3:22' },
      { position: '6', title: 'Juno! 무지개 좌표를 알려줘!', duration: '1:36' },
      { position: '7', title: '모든 소년 소녀들1 : 버드맨', duration: '3:45' },
      { position: '8', title: '모든 소년 소녀들2 : 무지개 ', duration: '4:56' },
    ],
  },
  {
    discogs_id: '34886606',
    album_name: 'Ruby',
    artist_name: 'Jennie (8)',
    cover_url:
      'https://i.discogs.com/BKtvaa11iI_iJnjJgoTqszbRr0mzWqmipqAiYM4MzZ4/rs:fit/g:sm/q:90/h:601/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM0ODg2/NjA2LTE3NTU4NDEy/MzMtNjc0Ni5qcGVn.jpeg',
    year: '2025',
    genres: ['Electronic', 'Hip Hop', 'Funk / Soul', 'Pop'],
    tracklist: [
      { position: 'A1', title: 'Intro: JANE With FKJ', duration: '' },
      { position: 'A2', title: 'like JENNIE', duration: '' },
      { position: 'A3', title: 'start a war', duration: '' },
      { position: 'A4', title: 'Handlebars (feat. Dua Lipa)', duration: '' },
      { position: 'A5', title: 'with the IE (way up)', duration: '' },
      { position: 'A6', title: 'ExtraL (feat. Doechii)', duration: '' },
      { position: 'A7', title: 'Mantra', duration: '' },
      { position: 'A8', title: 'Long Hangover (feat. Dominic Fike)', duration: '' },
      { position: 'B1', title: 'ZEN', duration: '' },
      { position: 'B2', title: 'Damn Right (feat. Childish Gambino & Kali Uchis)', duration: '' },
      { position: 'B3', title: 'F.T.S.', duration: '' },
      { position: 'B4', title: 'Filter', duration: '' },
      { position: 'B5', title: 'Seoul City', duration: '' },
      { position: 'B6', title: 'Starlight', duration: '' },
      { position: 'B7', title: 'twin', duration: '' },
    ],
  },
  {
    discogs_id: '35648713',
    album_name: '사운드 오브 뮤직 pt.2 : Life',
    artist_name: '잔나비',
    cover_url:
      'https://i.discogs.com/9Q2REm4FMsoRNwtphMbZ8ggxTdaXpV6g2rDpAv68ATA/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM1NjQ4/NzEzLTE3NjMwMDc1/MTAtNTk4OC5qcGVn.jpeg',
    year: '2025',
    genres: ['Rock', 'Pop', 'Folk, World, & Country'],
    tracklist: [
      { position: '1', title: '어스', duration: '1:59' },
      { position: '2', title: '애프터스쿨 액티비티', duration: '2:23' },
      { position: '3', title: '첫사랑은 안녕히-', duration: '4:06' },
      { position: '4', title: '오 뉴욕시티', duration: '1:32' },
      { position: '5', title: '잭 케루악 (feat. 양희은)', duration: '3:22' },
      { position: '6', title: '마더 (feat. 이수현)', duration: '3:37' },
      { position: '7', title: '산사람', duration: '2:53' },
      { position: '8', title: '여름에 관한 무용담 I', duration: '5:33' },
      {
        position: '9',
        title: '여름밤 차력쇼를 위한 TV 광고: 스웨트 앤 스타더스트 (skit)',
        duration: '0:30',
      },
      { position: '10', title: '미아의 추억과 유니버스', duration: '3:48' },
      { position: '11', title: '모든 소년 소녀들3 : 글로리', duration: '2:57' },
      { position: '12', title: '사운드 오브 뮤직', duration: '3:49' },
    ],
  },
  {
    discogs_id: '668094',
    album_name: 'Lemon Tree',
    artist_name: "Fool's Garden",
    cover_url:
      'https://i.discogs.com/Pc2iK3hTHJuDslsSvVCNJrfQdS3uLVWnzXrgfuNgxO8/rs:fit/g:sm/q:90/h:597/w:592/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTY2ODA5/NC0xNTg1ODQ0MjU1/LTg3OTYucG5n.jpeg',
    year: '1996',
    genres: ['Rock'],
    tracklist: [
      { position: '1', title: 'Lemon Tree', duration: '3:11' },
      { position: '2', title: 'Finally', duration: '4:29' },
    ],
  },
]
